/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Interfaces.warObserver;

/**
 *
 * @author hp
 */
public class Helicopter extends javax.swing.JFrame implements warObserver {

    boolean isCheckedPosition = false;
    private Maincontroller main;

    public Helicopter(Maincontroller main) {
        initComponents();
        this.main=main;
        setTitle("Helicopter");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocation(680, 30);
        setVisible(true);
        laserbtnh.setEnabled(false);
        missilebtnh.setEnabled(false);
        shootbtnh.setEnabled(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areatext = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreahelicopter = new javax.swing.JTextArea();
        jTextFieldhelicopter = new javax.swing.JTextField();
        sendbtnh = new javax.swing.JButton();
        shootbtnh = new javax.swing.JButton();
        laserbtnh = new javax.swing.JButton();
        missilebtnh = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        soldiertext = new javax.swing.JLabel();
        ammotext = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        positionhelicopter = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Helicopter");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        areatext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        areatext.setForeground(new java.awt.Color(255, 255, 255));
        areatext.setText("Area Not Cleared");
        getContentPane().add(areatext, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jTextAreahelicopter.setColumns(20);
        jTextAreahelicopter.setRows(5);
        jScrollPane1.setViewportView(jTextAreahelicopter);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 134, 355, 140));
        getContentPane().add(jTextFieldhelicopter, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 286, 287, -1));

        sendbtnh.setBackground(new java.awt.Color(255, 0, 51));
        sendbtnh.setFont(new java.awt.Font("Humnst777 BlkCn BT", 0, 12)); // NOI18N
        sendbtnh.setText("Send");
        sendbtnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbtnhActionPerformed(evt);
            }
        });
        getContentPane().add(sendbtnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 287, 62, -1));

        shootbtnh.setBackground(new java.awt.Color(0, 0, 0));
        shootbtnh.setFont(new java.awt.Font("Myriad Pro Light", 0, 12)); // NOI18N
        shootbtnh.setForeground(new java.awt.Color(255, 255, 0));
        shootbtnh.setText("Shoot");
        shootbtnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shootbtnhActionPerformed(evt);
            }
        });
        getContentPane().add(shootbtnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 123, 37));

        laserbtnh.setBackground(new java.awt.Color(0, 0, 0));
        laserbtnh.setFont(new java.awt.Font("Myriad Pro Light", 0, 12)); // NOI18N
        laserbtnh.setForeground(new java.awt.Color(255, 255, 0));
        laserbtnh.setText("Laser Operation");
        laserbtnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laserbtnhActionPerformed(evt);
            }
        });
        getContentPane().add(laserbtnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 85, 123, 37));

        missilebtnh.setBackground(new java.awt.Color(0, 0, 0));
        missilebtnh.setFont(new java.awt.Font("Myriad Pro Light", 0, 12)); // NOI18N
        missilebtnh.setForeground(new java.awt.Color(255, 255, 0));
        missilebtnh.setText("Missile Operation");
        missilebtnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                missilebtnhActionPerformed(evt);
            }
        });
        getContentPane().add(missilebtnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 40, 123, 37));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 6, -1, 28));
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 52, -1, 28));

        soldiertext.setForeground(new java.awt.Color(0, 255, 0));
        soldiertext.setText("Soldier Count");
        getContentPane().add(soldiertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 12, -1, -1));

        ammotext.setForeground(new java.awt.Color(51, 255, 0));
        ammotext.setText("Ammo Count");
        getContentPane().add(ammotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 58, -1, -1));

        jSlider1.setForeground(new java.awt.Color(255, 0, 0));
        jSlider1.setMajorTickSpacing(20);
        jSlider1.setMinorTickSpacing(10);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(100);
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 16, 58, 292));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 16, -1, -1));

        positionhelicopter.setForeground(new java.awt.Color(255, 255, 255));
        positionhelicopter.setText("Position");
        positionhelicopter.setContentAreaFilled(false);
        positionhelicopter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionhelicopterActionPerformed(evt);
            }
        });
        getContentPane().add(positionhelicopter, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 98, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Call of Duty_ Modern Warfare II Worldwide Reveal Trailer.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendbtnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbtnhActionPerformed
        main.setMessageheli(" "+jTextFieldhelicopter.getText());
    }//GEN-LAST:event_sendbtnhActionPerformed

    private void laserbtnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laserbtnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laserbtnhActionPerformed

    private void missilebtnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_missilebtnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_missilebtnhActionPerformed

    private void shootbtnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shootbtnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shootbtnhActionPerformed

    private void positionhelicopterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionhelicopterActionPerformed
            isCheckedPosition = positionhelicopter.isSelected();
    }//GEN-LAST:event_positionhelicopterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ammotext;
    private javax.swing.JLabel areatext;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextAreahelicopter;
    private javax.swing.JTextField jTextFieldhelicopter;
    private javax.swing.JButton laserbtnh;
    private javax.swing.JButton missilebtnh;
    private javax.swing.JCheckBox positionhelicopter;
    private javax.swing.JButton sendbtnh;
    private javax.swing.JButton shootbtnh;
    private javax.swing.JLabel soldiertext;
    // End of variables declaration//GEN-END:variables

    @Override
     public void setAreaClear(boolean isChecked){
        if (isChecked) {
            areatext.setText("Area Cleared");
        }else{
            areatext.setText("Area Not Cleared");
        }
    }
    @Override
    public void setActivateButtons(int value) {
        if (isCheckedPosition) {
            if (value>25) {
                shootbtnh.setEnabled(true);
            }else{
                shootbtnh.setEnabled(false);
            }
            if (value>50) {
                missilebtnh.setEnabled(true);
            }else{
                missilebtnh.setEnabled(false);
            }
            if (value>75) {
                laserbtnh.setEnabled(true);
            }else{
                laserbtnh.setEnabled(false);
            }
        }
    }

    @Override
    public void setMessageFromMainController(String message) {
        jTextAreahelicopter.setText(message);
    }
}
