/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Interfaces.warObserver;

/**
 *
 * @author hp
 */
public class Tank extends javax.swing.JFrame implements warObserver{

    boolean isCheckedPosition = false;
    private Maincontroller main;

    public Tank(Maincontroller main) {
        initComponents();
        this.main=main;
        setTitle("Tank");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocation(700, 420);
        setVisible(true);
        missilebtnt.setEnabled(false);
        redarbtnt.setEnabled(false);
        rotatebtnht.setEnabled(false);
        shootbtnt.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areatexttank = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTank = new javax.swing.JTextArea();
        jTextFieldTank = new javax.swing.JTextField();
        sendbtnh = new javax.swing.JButton();
        shootbtnt = new javax.swing.JButton();
        redarbtnt = new javax.swing.JButton();
        missilebtnt = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        soldiertext = new javax.swing.JLabel();
        ammotext = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        rotatebtnht = new javax.swing.JButton();
        positiontank = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tank");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        areatexttank.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        areatexttank.setForeground(new java.awt.Color(255, 255, 255));
        areatexttank.setText("Area Not Cleared");
        getContentPane().add(areatexttank, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jTextAreaTank.setColumns(20);
        jTextAreaTank.setRows(5);
        jScrollPane1.setViewportView(jTextAreaTank);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 134, 355, 140));
        getContentPane().add(jTextFieldTank, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 292, 287, -1));

        sendbtnh.setBackground(new java.awt.Color(255, 0, 51));
        sendbtnh.setFont(new java.awt.Font("Humnst777 BlkCn BT", 0, 12)); // NOI18N
        sendbtnh.setText("Send");
        sendbtnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbtnhActionPerformed(evt);
            }
        });
        getContentPane().add(sendbtnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 293, 62, -1));

        shootbtnt.setBackground(new java.awt.Color(0, 0, 0));
        shootbtnt.setFont(new java.awt.Font("Myriad Pro Light", 0, 12)); // NOI18N
        shootbtnt.setForeground(new java.awt.Color(255, 255, 0));
        shootbtnt.setText("Shoot");
        shootbtnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shootbtntActionPerformed(evt);
            }
        });
        getContentPane().add(shootbtnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, 123, 37));

        redarbtnt.setBackground(new java.awt.Color(0, 0, 0));
        redarbtnt.setFont(new java.awt.Font("Myriad Pro Light", 0, 12)); // NOI18N
        redarbtnt.setForeground(new java.awt.Color(255, 255, 0));
        redarbtnt.setText("Redar Operation");
        redarbtnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redarbtntActionPerformed(evt);
            }
        });
        getContentPane().add(redarbtnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 85, 123, 37));

        missilebtnt.setBackground(new java.awt.Color(0, 0, 0));
        missilebtnt.setFont(new java.awt.Font("Myriad Pro Light", 0, 12)); // NOI18N
        missilebtnt.setForeground(new java.awt.Color(255, 255, 0));
        missilebtnt.setText("Missile Operation");
        missilebtnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                missilebtntActionPerformed(evt);
            }
        });
        getContentPane().add(missilebtnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 40, 123, 37));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 6, -1, 28));
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 52, -1, 28));

        soldiertext.setForeground(new java.awt.Color(0, 255, 0));
        soldiertext.setText("Soldier Count");
        getContentPane().add(soldiertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 12, -1, -1));

        ammotext.setForeground(new java.awt.Color(0, 255, 0));
        ammotext.setText("Ammo Count");
        getContentPane().add(ammotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 58, -1, -1));

        jSlider1.setForeground(new java.awt.Color(255, 0, 0));
        jSlider1.setMajorTickSpacing(20);
        jSlider1.setMinorTickSpacing(10);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(100);
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 22, 58, 292));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 16, -1, -1));

        rotatebtnht.setBackground(new java.awt.Color(0, 0, 0));
        rotatebtnht.setFont(new java.awt.Font("Myriad Pro Light", 0, 12)); // NOI18N
        rotatebtnht.setForeground(new java.awt.Color(255, 255, 0));
        rotatebtnht.setText("Rotate Shootion");
        rotatebtnht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotatebtnhtActionPerformed(evt);
            }
        });
        getContentPane().add(rotatebtnht, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 85, 123, 37));

        positiontank.setForeground(new java.awt.Color(255, 255, 255));
        positiontank.setText("Position");
        positiontank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positiontankActionPerformed(evt);
            }
        });
        getContentPane().add(positiontank, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 98, 85, -1));

        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Call of Duty_ Modern Warfare II Worldwide Reveal Trailer.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendbtnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbtnhActionPerformed
        main.setMessagetank(" "+ jTextFieldTank.getText());
    }//GEN-LAST:event_sendbtnhActionPerformed

    private void redarbtntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redarbtntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redarbtntActionPerformed

    private void missilebtntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_missilebtntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_missilebtntActionPerformed

    private void shootbtntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shootbtntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shootbtntActionPerformed

    private void rotatebtnhtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotatebtnhtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rotatebtnhtActionPerformed

    private void positiontankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positiontankActionPerformed
         isCheckedPosition = positiontank.isSelected();
    }//GEN-LAST:event_positiontankActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ammotext;
    private javax.swing.JLabel areatexttank;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextAreaTank;
    private javax.swing.JTextField jTextFieldTank;
    private javax.swing.JButton missilebtnt;
    private javax.swing.JCheckBox positiontank;
    private javax.swing.JButton redarbtnt;
    private javax.swing.JButton rotatebtnht;
    private javax.swing.JButton sendbtnh;
    private javax.swing.JButton shootbtnt;
    private javax.swing.JLabel soldiertext;
    // End of variables declaration//GEN-END:variables

    public void setAreaClear(boolean isChecked){
        if (isChecked) {
            areatexttank.setText("Area Cleared");
        }else{
            areatexttank.setText("Area Not Cleared");
        }
    }

    @Override
    public void setActivateButtons(int value) {
        if (isCheckedPosition) {
            if (value>20) {
                shootbtnt.setEnabled(true);
            }else{
                shootbtnt.setEnabled(false);
            }
            if (value>40) {
                missilebtnt.setEnabled(true);
            }else{
                missilebtnt.setEnabled(false);
            }
            if (value>60) {
                redarbtnt.setEnabled(true);
            }else{
                redarbtnt.setEnabled(false);
            }
            if (value>80) {
                rotatebtnht.setEnabled(true);
            }else{
                rotatebtnht.setEnabled(false);
            }
        }
    }

    @Override
    public void setMessageFromMainController(String message) {
        jTextAreaTank.setText(message);
    }
}
